livspaceeng/helm-charts

charts/hydra/Chart.yaml
charts/hydra/templates/ingress.yaml

Upgraded ingress apiVersion in hydra

---

charts/hydra/Chart.yaml

Hydra release update

---

charts/boundary/.helmignore
charts/boundary/Chart.yaml
charts/boundary/templates/NOTES.txt
charts/boundary/templates/_boundary.tpl
charts/boundary/templates/_helpers.tpl
charts/boundary/templates/controller-configmap.yaml
charts/boundary/templates/controller-deployment.yaml
charts/boundary/templates/controller-hpa.yaml
charts/boundary/templates/controller-ingress.yaml
charts/boundary/templates/controller-service.yaml
charts/boundary/templates/database-init-job.yaml
charts/boundary/templates/rbac.yaml
charts/boundary/templates/serviceaccount.yaml
charts/boundary/templates/worker-configmap.yaml
charts/boundary/templates/worker-deployment.yaml
charts/boundary/templates/worker-hpa.yaml
charts/boundary/templates/worker-service.yaml
charts/boundary/values.schema.json
charts/boundary/values.yaml

Added boundary charts

---

charts/convoy/Chart.yaml
charts/convoy/templates/ingress.yaml

convoy ingress fix for label

---

charts/convoy/Chart.yaml
charts/convoy/templates/NOTES.txt

Ganarajtejasvi patch 1

---

charts/convoy/Chart.yaml
charts/convoy/templates/deployment.yaml

convoy added pod labels values

---

charts/convoy/Chart.yaml
charts/convoy/templates/deployment.yaml

convoy pod labels

---

charts/convoy/Chart.yaml
charts/convoy/templates/configmap.yaml

configmap template fix

---

charts/hydra/Chart.yaml
charts/hydra/templates/pdb.yaml
charts/hydra/values.yaml

Added pod disruption budget for hydra.

PDB for hydra

---

charts/rudderstack/Chart.yaml
charts/rudderstack/templates/service.yaml
charts/rudderstack/values.yaml

Provision to conditionally add a service to a rudderstack app

---

charts/rudderstack/Chart.yaml
charts/rudderstack/templates/service.yaml

Removed comment from service.yaml

---

charts/hydra/Chart.yaml
charts/hydra/templates/janitor-cronjob.yaml
charts/hydra/values.yaml

Introduced [janitor](https://www.ory.sh/docs/hydra/cli/hydra-janitor#hydra-janitor) in hydra

Introduced janitor in hydra

---

charts/boundary/Chart.yaml
charts/boundary/templates/controller-deployment.yaml
charts/boundary/templates/database-init-job.yaml
charts/boundary/values.yaml

Added if condition for initContainer in boundary-controller-deployment as it was getting stuck whenever new b-controller pod was getting created. Job mentioned in InitContainer is required incase of boundary version update .

fix: Added condition for running controllers init container

---

.github/workflows/release.yaml
charts/app-compat/Chart.yaml
charts/app-compat/templates/apisix-route.yaml
charts/app-compat/values.yaml

app-compat release

---

charts/app-compat/Chart.yaml
charts/app-compat/schema.json
charts/app-compat/templates/deployment.yaml
charts/app-compat/templates/serviceaccount.yaml
charts/app-compat/values.yaml

Add values to control automountServiceAccountToken on serviceaccount and pod.

Values to control automount of service account token. Disable by default

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/deployment.yaml

JIRA: https://livspaceengg.atlassian.net/browse/IN-1800

fix: updated initcontainers in templates/deployment.yaml

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/deployment.yaml

JIRA: https://livspaceengg.atlassian.net/browse/IN-1801

fix: updated initcontainers in templates/deployment.yaml and increment chart version in next branch of helm-charts repo 

---

charts/liv-chat/Chart.yaml
charts/liv-chat/templates/deployment.yaml
charts/liv-chat/templates/scc-broker-deployment.yaml
charts/liv-chat/templates/scc-state-deployment.yaml
charts/liv-chat/values.yaml

[liv-chat helm chart] - added team lablel in deployment.yaml

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/deployment.yaml

[app-compat] - added livcr and tags to gtoken containers

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/deployment.yaml

[app-compat] - next branch - Added livcr and label tag

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/servicemonitor.yaml
charts/app-compat/values.yaml

[app-compat helm-chart] - added service-monitor.yaml

---

charts/liv-chat/Chart.yaml
charts/liv-chat/templates/service.yaml

JIRA: https://livspaceengg.atlassian.net/browse/IN-1956

[liv-chat helm chart] - added team label in service.yaml

---

charts/liv-chat/Chart.yaml
charts/liv-chat/templates/scc-broker-service.yaml
charts/liv-chat/templates/scc-state-service.yaml

[liv-chat helm chart] - added team labels to broker and state service.yaml

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/servicemonitor.yaml
charts/app-compat/values.yaml

updated the servicemonitor.yaml 

[app-compat helm-chart] - updated servicemonitor spec

---

charts/liv-chat/Chart.yaml
charts/liv-chat/templates/networkpolicy.yaml
charts/liv-chat/values.yaml

JIRA: https://livspaceengg.atlassian.net/browse/IN-2049

[liv-chat helm chart] - added CNP(networkpolicy.yaml) to liv-chat helm chart

---

charts/socket-cluster/Chart.yaml
charts/socket-cluster/templates/networkpolicy.yaml
charts/socket-cluster/templates/scc-broker-service.yaml
charts/socket-cluster/templates/scc-state-service.yaml
charts/socket-cluster/values.yaml

[socket-cluster] - Updated socket-cluster helm chart - added CNP and labels in service

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/deployment.yaml
charts/app-compat/values.yaml

JIRA: https://livspaceengg.atlassian.net/browse/DO-18

[app-compat Helm Chart] - Added default topology spread constraint

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/deployment.yaml
charts/app-compat/values.yaml

JIRA: https://livspaceengg.atlassian.net/browse/DO-18

[app-compat Helm Chart] - updated default topology key in values.yaml

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/deployment.yaml

JIRA: https://livspaceengg.atlassian.net/browse/DO-18

[app-compat Helm Chart] - add conditions for appId and envId in deployment.yaml for topologySpreadConstraints

---

charts/hydra/Chart.yaml
charts/hydra/templates/deployment.yaml
charts/hydra/values.yaml

JIRA: https://livspaceengg.atlassian.net/browse/DO-38

[hydra-helm-chart] - Added preStop and postStart hooks in hydra deployment.yaml

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/deployment.yaml
charts/app-compat/templates/external-secrets-v2.yaml
charts/app-compat/templates/statefulset.yaml
charts/app-compat/values.yaml

add support for externalSecrets through new secret-management repo

---

charts/app-compat/Chart.yaml
charts/app-compat/templates/deployment.yaml
charts/app-compat/values.yaml

chore: add a check for externalSecretsv2 key in app-compat chart
